"""
Django settings for cerebro project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure--ik_0w-0p5wdx09d+h4qwr!$uwysdi-f8gvkwr@1zb@rqq)yy5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get('DEBUG', True))

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1').split(' ')

if os.environ.get('CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS = [os.environ.get('CSRF_TRUSTED_ORIGINS')]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'search',
    'help',
    'statistic',
    'versions',
    'databases',
    'user'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cerebro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'statistic.context_processors.get_statistic',
                'search.context_processors.ping_elasticsearch',
                'search.context_processors.tasks_elasticsearch',
            ],
        },
    },
]

WSGI_APPLICATION = 'cerebro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('SQL_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('SQL_DATABASE', os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': os.environ.get('SQL_USER', 'user'),
        'PASSWORD': os.environ.get('SQL_PASSWORD', 'password'),
        'HOST': os.environ.get('SQL_HOST', 'localhost'),
        'PORT': os.environ.get('SQL_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'user.User'


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

DATETIME_FORMAT = 'd.m.Y H:i'

USE_I18N = True

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, "static"),
# )

STATIC_ROOT = BASE_DIR / 'static/'

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


"""
Custom project settings
"""

# Redirect before login or logout
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Setting session lifetime (default 30 min)
SESSION_COOKIE_AGE = 1800


# Elastic settings
ELASTIC_CERT_FINGERPRINT = os.environ.get('ELASTIC_CERT_FINGERPRINT', 'A0:C4:DA:D7:AD:B2:7B:D9:AA:48:AC:91:3E:0E:9E:0F:05:80:2B:EC:75:80:C9:27:43:52:49:04:8D:6E:3A:DB')
ELASTIC_USER = {
    'username': os.environ.get('ELASTIC_USERNAME', 'elastic'),
    'password': os.environ.get('ELASTIC_PASSWORD', 'O11J4soaIrTTUUQhT9Vp')
}
ELASTIC_SERVER = os.environ.get('ELASTIC_SERVER', 'https://10.0.0.2:9200')


# Pagination setting
DOCUMENTS_COUNT = 150
RESULTS_PER_PAGE = 15


# Search results
DOCUMENTS_RESULTS = 500


# Logging settings
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs.log',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Configurator settings
PATH_CONFIGURATOR_CONFIG = 'config.json'
PATH_CONFIGURATOR_MAPPINGS = 'mappings.json'
MAPPINGS_PATH = 'static/js/mappings.json'
MAPPINGS = [
    {
        'field': 'name',
        'title': 'Имя',
        'checked': 0
    },
    {
        'field': 'sex',
        'title': 'Пол',
        'checked': 0
    },
    {
        'field': 'birth_date',
        'title': 'Дата рождения',
        'checked': 0
    },
    {
        'field': 'birth_place',
        'title': 'Место рождения',
        'checked': 0
    },
    {
        'field': 'country',
        'title': 'Страна',
        'checked': 0
    },
    {
        'field': 'address',
        'title': 'Адрес',
        'checked': 0
    },
    {
        'field': 'relationship',
        'title': 'Статус отношений',
        'checked': 0
    },
    {
        'field': 'childrens',
        'title': 'Дети',
        'checked': 0
    },
    {
        'field': 'phones',
        'title': 'Телефон(-ы)',
        'checked': 0
    },
    {
        'field': 'emails',
        'title': 'E-mails',
        'checked': 0
    },
    {
        'field': 'socials',
        'title': 'Социальные сети',
        'checked': 0
    },
    {
        'field': 'educations',
        'title': 'Образование',
        'checked': 0
    },
    {
        'field': 'works',
        'title': 'Работа',
        'checked': 0
    },
    {
        'field': 'documents',
        'title': 'Документы',
        'checked': 0
    },
    {
        'field': 'cars_status',
        'title': 'Наличие авто',
        'checked': 0
    },
    {
        'field': 'cars',
        'title': 'Авто',
        'checked': 0
    },
    {
        'field': 'banks',
        'title': 'Платежные системы и банки',
        'checked': 0
    },
    {
        'field': 'ownerships',
        'title': 'Собственность',
        'checked': 0
    },
    {
        'field': 'links',
        'title': 'Ссылки',
        'checked': 0
    },
    {
        'field': 'accounts',
        'title': 'Аккаунты',
        'checked': 0
    },
    {
        'field': 'ip',
        'title': 'IP',
        'checked': 0
    },
    {
        'field': 'coordinates',
        'title': 'Координаты',
        'checked': 0
    },
    {
        'field': 'comment',
        'title': 'Комментарий',
        'checked': 0
    },
    {
        'field': 'database',
        'title': 'База данных',
        'checked': 1
    },
    {
        'field': 'status',
        'title': 'Статус',
        'checked': 1
    },
    {
        'field': 'category',
        'title': 'Категория',
        'checked': 1
    },
    {
        'field': 'tags',
        'title': 'Теги',
        'checked': 0
    },
    {
        'field': 'date',
        'title': 'Дата',
        'checked': 1
    }
]

DOCUMENTS_CATEGORY = {
    0: {
        'title': 'Человек',
        'icon': """
            <span class="svg-icon">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6.28548 15.0861C7.34369 13.1814 9.35142 12 11.5304 12H12.4696C14.6486 12 16.6563 13.1814 17.7145 15.0861L19.3493 18.0287C20.0899 19.3618 19.1259 21 17.601 21H6.39903C4.87406 21 3.91012 19.3618 4.65071 18.0287L6.28548 15.0861Z" fill="currentColor"/>
                    <rect opacity="0.3" x="8" y="3" width="8" height="8" rx="4" fill="currentColor"/>
                </svg>
            </span>
        """
    },
    1: {
        'title': 'Социальный профиль',
        'icon': """
            <span class="svg-icon">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path opacity="0.3" d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" fill="currentColor"/>
                    <path d="M13.643 9.36206C13.6427 9.05034 13.7663 8.75122 13.9864 8.53052C14.2065 8.30982 14.5053 8.18559 14.817 8.18506H15.992V5.23999H13.643C13.1796 5.24052 12.7209 5.33229 12.293 5.51013C11.8651 5.68798 11.4764 5.94841 11.1491 6.27649C10.8219 6.60457 10.5625 6.99389 10.3857 7.42224C10.209 7.85059 10.1183 8.30956 10.119 8.77295V11.718H7.769V14.663H10.119V21.817C11.2812 22.0479 12.4762 22.0604 13.643 21.854V14.663H15.992L17.167 11.718H13.643V9.36206Z" fill="currentColor"/>
                </svg>
            </span>
        """
    },
    2: {
        'title': 'Политик',
        'icon': """
            <span class="svg-icon">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path opacity="0.3" d="M18 22C19.7 22 21 20.7 21 19C21 18.5 20.9 18.1 20.7 17.7L15.3 6.30005C15.1 5.90005 15 5.5 15 5C15 3.3 16.3 2 18 2H6C4.3 2 3 3.3 3 5C3 5.5 3.1 5.90005 3.3 6.30005L8.7 17.7C8.9 18.1 9 18.5 9 19C9 20.7 7.7 22 6 22H18Z" fill="currentColor"/>
                    <path d="M18 2C19.7 2 21 3.3 21 5H9C9 3.3 7.7 2 6 2H18Z" fill="currentColor"/>
                    <path d="M9 19C9 20.7 7.7 22 6 22C4.3 22 3 20.7 3 19H9Z" fill="currentColor"/>
                </svg>
            </span>
        """
    },
    3: {
        'title': 'Военнослужащий',
        'icon': """
            <span class="svg-icon">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path opacity="0.3" d="M21 11H18.9C18.5 7.9 16 5.49998 13 5.09998V3C13 2.4 12.6 2 12 2C11.4 2 11 2.4 11 3V5.09998C7.9 5.49998 5.50001 8 5.10001 11H3C2.4 11 2 11.4 2 12C2 12.6 2.4 13 3 13H5.10001C5.50001 16.1 8 18.4999 11 18.8999V21C11 21.6 11.4 22 12 22C12.6 22 13 21.6 13 21V18.8999C16.1 18.4999 18.5 16 18.9 13H21C21.6 13 22 12.6 22 12C22 11.4 21.6 11 21 11ZM12 17C9.2 17 7 14.8 7 12C7 9.2 9.2 7 12 7C14.8 7 17 9.2 17 12C17 14.8 14.8 17 12 17Z" fill="currentColor"/>
                    <path d="M12 15C13.6569 15 15 13.6569 15 12C15 10.3431 13.6569 9 12 9C10.3431 9 9 10.3431 9 12C9 13.6569 10.3431 15 12 15Z" fill="currentColor"/>
                </svg>
            </span>
        """
    }
}